---
- name: Remove Wireless Access Point (WAP)
  hosts: localhost
  become: yes
  tasks:
    - name: Stop hostapd services
      service:
        name: "{{ item }}"
        state: stopped
      loop:
        - hostapd

    - name: Disable hostapd at boot
      service:
        name: "{{ item }}"
        enabled: no
      loop:
        - hostapd

    - name: Remove WAP configuration file
      file:
        path: /etc/hostapd/hostapd.conf
        state: absent

    - name: Remove WAP configuration from network interfaces
      replace:
        path: /etc/network/interfaces
        regexp: "^(allow-hotplug wlan0|iface wlan0 inet manual|iface wlan0 inet static|address 192.168.1.1|netmask 255.255.255.0).*$"
        replace: ""

    - name: Restart networking service
      service:
        name: networking
        state: restarted
