---
- name: Configure Hotspot Wi-Fi
  hosts: localhost
  become: yes

  tasks:

    - name: Create accesspoint directory
      command: mkdir /etc/accesspoint
      become: yes
      ignore_errors: yes

    - name: Set accesspoint config
      template:
        src: accesspoint.json
        dest: /etc/accesspoint/accesspoint.json
      become: yes

    - name: Set accesspoint hostapd
      template:
        src: hostapd.config
        dest: /etc/accesspoint/hostapd.config
      become: yes

    - name: Start accesspoint
      command: pyaccesspoint --config -v start
      become: yes
