---
- name: Configure Wireless Access Point
  hosts: localhost
  become: yes
  vars:
    ssid: "{{ ssid }}"
  tasks:
    - name: Check if connected to Wi-Fi
      command: iwgetid -r
      register: wifi_ssid
      ignore_errors: yes

    - name: Disconnect from Wi-Fi if connected
      command: nmcli connection down "{{ wifi_ssid.stdout }}"
      when: wifi_ssid.stdout is defined
      ignore_errors: yes
    
    - name: Install necessary packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - hostapd

    - name: Stop hostapd server services
      service:
        name: "{{ item }}"
        state: stopped
      loop:
        - hostapd

    - name: Unmask hostapd server services
      service:
        name: "{{ item }}"
        state: unmask
      loop:
        - hostapd
      ignore_errors: yes

    - name: Configure network interface
      lineinfile:
        path: /etc/network/interfaces
        line: "{{ item }}"
      loop:
        - "allow-hotplug wlan0"
        - "iface wlan0 inet static"
        - "address 192.168.1.1"
        - "netmask 255.255.255.0"

    - name: Restart networking service
      service:
        name: networking
        state: restarted

    - name: Configure hostapd
      copy:
        dest: /etc/hostapd/hostapd.conf
        content: |
            interface=wlan0
            ssid={{ ssid }}
            hw_mode=g
            channel=6
            macaddr_acl=0
            auth_algs=1
            ignore_broadcast_ssid=0
            wpa=0

    - name: Update hostapd configuration file path
      lineinfile:
        path: /etc/default/hostapd
        line: "DAEMON_CONF='/etc/hostapd/hostapd.conf'"

    - name: Start hostapd server services
      service:
        name: "{{ item }}"
        state: started
      loop:
        - hostapd

    - name: Enable hostapd server at boot
      service:
        name: "{{ item }}"
        enabled: yes
      loop:
        - hostapd
