---
- name: Connect to Wi-Fi Network
  hosts: localhost
  become: yes
  tasks:
    - name: Enable Wi-Fi
      command: nmcli radio wifi on
      ignore_errors: yes

    - name: Connect to Wi-Fi Network
      command: nmcli dev wifi connect "{{ ssid }}" password "{{ password }}" iface wlan0
